# Generated by Django 5.0.7 on 2024-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default="2023-01-01 00:00:00"
            ),
            preserve_default=False,
        ),
    ]
