# Generated by Django 5.0.7 on 2024-07-19 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
    ]
