# Generated by Django 5.0.7 on 2024-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_listing_starting_bid_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="starting_bid",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
