# Generated by Django 5.0.7 on 2024-07-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_listing_starting_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="final_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
