# Generated by Django 5.0.7 on 2024-08-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_comment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="commenter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commenter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
